### ISSUE TITLE
401 Authorization Required

### ISSUE THREAD

**Issue by ghost** [LuochuanAD/LCWebView#1]
加载一些需要认证的网页会返回401

**Comment by LuochuanAD** [comment]
谢谢，我会记下这个问题，那么是否可以提供一个网页链接，或者发到我邮箱。以便于我能更快的就行测试。

**Comment by ghost** [comment]
这里有解决方案：https://github.com/ShingoFukuyama/WKWebViewTips
至于链接不太好意思了，不方便😶😶😶

**Comment by LuochuanAD** [comment]
哈哈，我以为这个没人会用，我刚刚才看到，不好意思哈，我这周末就更新一下

**Comment by LuochuanAD** [comment]
已更新,你看下
