### ISSUE TITLE
现在这个版本，编译报错12个，请作者检查一下

### ISSUE THREAD

**Issue by hms040717007** [LuochuanAD/LCWebView#3]

**Comment by LuochuanAD** [comment]
好的，Xcode11没有对应，我以为没有人用，就没有更新了，那我这周末立刻更新。

**Comment by hms040717007** [comment]
谢谢，如果可以作者可以考虑出一个单独的WKWebView的工具项目，还有关于缓存的问题，可不可以设计一个开关（获取最新不要缓存和加载缓存的网页）

**Comment by LuochuanAD** [comment]
嗯嗯，关于缓存这个问题需求，仔细说说吧，可以控制哪个页面缓存，哪个页面不缓存吗？

**Comment by hms040717007** [comment]
是的最好有这个开关，是的。比如有的网页不需要频繁更新，那么加载一次就要缓存，以后从缓存加载；有的页面需要频繁修改或有这个需求需要加载最新的，那就需要不要从缓存取，每次都重新加载。

**Comment by LuochuanAD** [comment]
Xcode11 已对应, 编译报错没有了
